<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Exercise 10:</h1>
    <p>
      Handle an error thrown asynchronously in an asynchronous function using try...catch and async/await.
    </p>
    <p>note about the solution: in asynchronous functions, errors are encapsulated in rejected promised objects. Therefore, to catch the error, we use the catch method directly in the asynchronous function call.</p>

    <script src="index.js"></script>
  </body>
</html>
