<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Try...catch </h1>
  <p>The try...catch statement is comprised of a try block and either a catch block, a finally block, or both. The code in the try block is executed first, and if it throws an exception, the code in the catch block will be executed. The code in the finally block will always be executed before control flow exits the entire construct.</p>
  <p>The <strong>try</strong> statement always starts with a try block. Then, a catch block or a finally block must be present. It's also possible to have both catch and finally blocks. This gives us three forms for the try statement:
    <ul>
      <li>try...catch</li>
      <li>try...finally</li>
      <li>try...catch...finally</li>
    </ul>
    Unlike other constructs such as if or for, the try, catch, and finally blocks must be blocks, instead of single statements.</p>
    <p>A <strong>catch</strong> block contains statements that specify what to do if an exception is thrown in the try block. If any statement within the try block (or in a function called from within the try block) throws an exception, control is immediately shifted to the catch block. If no exception is thrown in the try block, the catch block is skipped.</p>
    <p>The <strong>finally</strong> block will always execute before control flow exits the try...catch...finally construct. It always executes, regardless of whether an exception was thrown or caught.</p>
    <p> You can nest one or more try statements. If an inner try statement does not have a catch block, the enclosing try statement's catch block is used instead.</p>
    <p>You can also use the try statement to handle JavaScript exceptions.</p>

    <h2>Throw</h2>
    <p>The throw statement throws a user-defined exception. Execution of the current function will stop (the statements after throw won't be executed), and control will be passed to the first catch block in the call stack. If no catch block exists among caller functions, the program will terminate.</p>
    <p><i>Syntax</i>:throw expression</p>
    <p><i>Example</i>:throw new Error("Required")</p>
    <p>In practice, the exception you throw should always be an Error object or an instance of an Error subclass, such as RangeError. This is because code that catches the error may expect certain properties, such as message, to be present on the caught value. For example, web APIs typically throw DOMException instances, which inherit from Error.prototype.</p>
    <h2>Error object</h2>
    <p><strong>Some error types</strong></p>
    <ul>
      <li><strong>Error</strong>:Creates a generic error, you can put a message. Like: throw new Error("An error was found here.")</li>
      <li><strong>RangeError</strong>:Creates an instance representing an error that occurs when a numeric variable or parameter is outside its valid range.</li>
      <li><strong>ReferenceError</strong>:Creates an instance representing an error that occurs when de-referencing an invalid reference.</li>
      <li><strong>SyntaxError</strong>:Creates an instance representing a syntax error.</li>
      <li><strong>TypeError</strong>:Creates an instance representing an error that occurs when a variable or parameter is not of a valid type.</li>
      
    </ul>
  <script src="index.js"></script>  
</body>
</html>